name: Convert PNGs to WebP

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install sharp
        run: npm install sharp

      - name: Convert all PNGs to WebP + delete originals + update references
        run: node convert-all-to-webp.mjs

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "auto: convert PNGs → WebP + delete originals + update refs" || echo "No changes"
          git push