name: Convert PNGs to WebP + Generate Frame Lists

on:
  push:
    paths:
      - 'assets/stopmotion/**.png'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Sharp
        run: npm install sharp

      - name: Convert PNGs to WebP + Generate frames.json
        run: node convert-to-webp.mjs

      - name: Commit generated assets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/stopmotion-webp
          git diff --cached --quiet || git commit -m "auto: convert PNGs + generate frames.json"
          git push